### ISSUE TITLE
Formulaire création dossier

### ISSUE THREAD

**Issue by williamsko** [Kodelines/dmp-front#10]
Modifier le formulaire d'ajout patient.

- Nouveau libellé : `Nouveau dossier patient`
- Les champs sont pour le moment disposés sur une seule colonne ce qui rend le formulaire trop long. Mettre les champs sur deux colonnes. Voici la liste des champs à prendre en compte : 

- Prénom(s)
- Nom
- Date et Lieu de naissance
- Sexe
- Situation matrimoniale
- Numéro de téléphone
- Type de pièce présenté à l'ouverture du dossier (Passeport, Permis de Conduire, Carte Nationale d'Identité,Carte consulaire, Carte d'étudiant)
- Numéro de la pièce
- Adresse complète
- Autre adresse
- Personne à prévenir en cas d'accident
    - Nom et Prénoms
    - Lien avec le patient
    - Numéro de téléphone
    - Adresse complète

**Comment by ymoussaba** [comment]
![Capture d’écran 2020-09-30 à 05 12 03](https://user-images.githubusercontent.com/4623563/94639045-98d32580-02db-11eb-85e0-fcb105630ac1.png)

Ce à quoi ça ressemble
