### ISSUE TITLE
[CONSULTATION] : Formulaire de saisie d'une consultation

### ISSUE THREAD

**Issue by williamsko** [Kodelines/dmp-front#4]
Le formulaire de saisie d'une nouvelle consultation doit s'afficher sur une autre page. et non dans une modale
Remplacer dans le formulaire le champ `Commentaire` par `Diagnostic`

**Comment by ymoussaba** [comment]
What does it look like
![Capture d’écran 2020-09-30 à 18 25 09](https://user-images.githubusercontent.com/4623563/94712929-6ca2bd80-034a-11eb-93d1-38d70523e3fe.png)
