### ISSUE TITLE
Bouton charger document

### ISSUE THREAD

**Issue by williamsko** [Kodelines/dmp-front#43]
Comme convenu, il faut créer un bouton charger document qui sera utilisé par d'autres acteurs de la santé afin d'ajouter des documents, images, photos , pdf à un dossier patient.. Le bouton devrait avoir la même taille que celui d'ajout d'un nouveau patient.

**Comment by ymoussaba** [comment]
En fait je suis d'accord sur le principe de la page et de son contenu, mais c'est l'accès qui ne me sied pas.
Ok pour démo visible tel quel, mais je pense qu'il faudrait revoir cela plus tard.
N'oublie pas que le gars censé ajouter des documents à un dossier patient, n'à pas accès à la plateforme, donc ne peux pas voir le dashboard, ni se connecter.
Du coup comme discuté dernièrement, je pense encore qu'il faut qu'on ai un tab dans le dossier patient, ou l'on pourra créer un lien unique avec token, limité dans le temps qui mènerait directement sur la page ajouté plus haut.
Après tout, de toute façon il faudrait déjà partagé au laborantin l'URL du site, donc on peut le faire one shot comme ça.

**Comment by williamsko** [comment]
Bon je pense qu'on s'est compris. du coup on peut fermer ce ticket
